### PR TITLE
Start with thank you page

### PR DESCRIPTION
**Pull request by mvr320**
@iMylene can you add the comics?

### CODE REVIEW

**Comment by iMylene** [comment]
Doesn't this PR removes the schedule page?

**Review by iMylene — CHANGES_REQUESTED** [review]
I want to keep the schedule.md page and add a thank you page instead.

**Review by EuiYeonJang — COMMENTED** [review]
It still removes schedule.md

**Comment by iMylene** [comment]
I don't know how to undo the changes in schedule.md. If I delete it, it removes schedule.md.

**Review by iMylene — APPROVED** [review]

**Pull request merged**
